-- Create the banners table
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  message TEXT NOT NULL,
  is_active BOOLEAN DEFAULT false,
  type TEXT DEFAULT 'warning' CHECK (type IN ('warning', 'info', 'error')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert a default row if it doesn't exist
INSERT INTO banners (id, message, is_active, type)
VALUES (1, 'Winter Storm Alert: Expect transport delays in affected regions.', false, 'warning')
ON CONFLICT (id) DO NOTHING;

-- Enable RLS
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read
CREATE POLICY "Public can read banners" ON banners
  FOR SELECT
  USING (true);

-- Policy: Only admins can update (adjust this based on your actual auth logic)
-- For now, allowing authenticated users to update for simplicity, or restricted to employees/admins
-- Assuming you have a role claim or public.profile role check:
-- CREATE POLICY "Admins can update banners" ON banners
--   FOR UPDATE
--   USING (auth.jwt() ->> 'role' = 'service_role' OR exists(select 1 from profiles where id = auth.uid() and role in ('admin', 'employee')));
-- For development/testing immediately without complex auth setup:
CREATE POLICY "Authenticated can update banners" ON banners
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);
